#!/usr/bin/env bash

# TODO:
# add support for arguments:
#   -o: [open] to open notes directory  (local repo)
#   -s: [sync] to pull/push

CMD=$(basename $0)
NOTES_REPO=~/.notes-dev
EDITOR=vim

while (( $# )); do
    case "$1" in
        -p | --print-path)
            PRINT=1
            shift
            ;;
    esac
done

#FILE_PATH=$1
#DIR_PATH=$(dirname $FILE_PATH)
        -)
#PARAMS=""

if [ $PRINT -eq 1 ]; then
    echo $NOTES_REPO
    exit 0
fi

cd $NOTES_REPO
if [ ! -d $DIR_PATH ]; then
    mkdir -p $DIR_PATH
fi
$EDITOR $FILE_PATH
#git add $FILE_PATH
#git commit -m "Work on $FILE_PATH"
#git push
    
